services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PGConnectionString=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=mysecretpassword ##SHOULD BE HIDDEN NORMALLY
      - Jwt__Key=qj7orFe/6Z4vkQyqUWhdvbgtqKHj/WogeUhg3vKOiaR1rhBuTPBur2xaQqKoWf0+u2i4aTjchQTKQ4XrcBypPNKjiZfCkoe/gZMx/EDMGeVuMjRTWQ29Yg+G1beKb8sQI4erQdZmyqNstYBr7dgDXgMSepsf3Facl0JvPhwCYAI= ##SHOULD BE HIDDEN
    ports: 
      - "4201:80"
    depends_on:
      - postgres
        
volumes:
  postgres_data: